# Generated by Django 6.1.1 on 2026-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0003_loginhistory_sitetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
