# Generated by Django 6.1.1 on 2026-09-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='applicable_for',
        ),
    ]
