# Generated by Django 6.1.1 on 2026-09-19 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0007_sitemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
