# Generated by Django 6.1.1 on 2026-09-19 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0008_role_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('site_code', models.CharField(max_length=50, unique=True)),
                ('site_name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=100)),
                ('site_image', models.ImageField(upload_to='site_images/%Y/%m/')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='vmsservices.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('site_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='vmsservices.sitemodel')),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='vmsservices.sitetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
