# Generated by Django 6.1.1 on 2026-09-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0009_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsites', to='vmsservices.site'),
        ),
    ]
