# Generated by Django 6.1.1 on 2026-09-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0010_site_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=200)),
                ('menu_enabled', models.BooleanField(default=False)),
                ('can_view_subsites', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='vmsservices.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_role_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('role', 'menu_key')},
            },
        ),
    ]
