# Generated by Django 6.1.1 on 2026-09-21 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0015_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identity_type_name', models.CharField(max_length=150, unique=True)),
                ('identity_number_validation', models.CharField(max_length=20)),
                ('identity_number_digits', models.PositiveIntegerField(blank=True, null=True)),
                ('identity_number_alphabets', models.PositiveIntegerField(blank=True, null=True)),
                ('identity_number_format', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number_validation', models.CharField(max_length=20)),
                ('phone_number_min', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number_max', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number_starting_with', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number_format', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_identity_types', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_identity_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
