# Generated by Django 6.1.1 on 2026-09-21 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0016_identitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key_no', models.CharField(max_length=50)),
                ('key_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Lost', 'Lost')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='vmsservices.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('site', 'key_no')},
            },
        ),
    ]
