# Generated by Django 6.1.1 on 2026-09-26 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0018_visitortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pass_no', models.CharField(max_length=50)),
                ('pass_type', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Assigned', 'Assigned'), ('Lost', 'Lost')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passes', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='vmsservices.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_passes', to=settings.AUTH_USER_MODEL)),
                ('visitor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='vmsservices.visitortype')),
            ],
            options={
                'unique_together': {('site', 'pass_no')},
            },
        ),
    ]
