# Generated by Django 6.1.1 on 2026-09-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0019_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='pass_type',
            new_name='pass_name',
        ),
    ]
