# Generated by Django 6.1.1 on 2026-09-29 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0021_tenantnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('identity_type', models.CharField(max_length=150)),
                ('identity_number', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currently_checked_in', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('WALK_IN', 'WALK_IN'), ('PRE_REGISTRATION', 'PRE_REGISTRATION'), ('PRE_REGISTRATION_BULK', 'PRE_REGISTRATION_BULK')], default='WALK_IN', max_length=30)),
                ('bulk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20, null=True)),
                ('requester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('pass_no', models.CharField(blank=True, default='', max_length=50)),
                ('key_no', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.site')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.tenant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.visitordetail')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('WALK_IN', 'WALK_IN'), ('PRE_REGISTRATION', 'PRE_REGISTRATION'), ('PRE_REGISTRATION_BULK', 'PRE_REGISTRATION_BULK')], default='WALK_IN', max_length=30)),
                ('bulk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=20, null=True)),
                ('requester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('pass_no', models.CharField(blank=True, default='', max_length=50)),
                ('key_no', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.site')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.tenant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.visitordetail')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
