# Generated by Django 6.1.1 on 2026-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0022_visitordetail_visitor_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
