# Generated by Django 6.1.1 on 2026-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0024_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='approver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
