# Generated by Django 6.1.1 on 2026-10-03 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0025_contractor_approver_email_visitor_approver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='approval_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='visitor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.visitortype'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approval_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='vmsservices.visitortype'),
        ),
    ]
