# Generated by Django 6.1.1 on 2026-10-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsservices', '0026_contractor_approval_remark_contractor_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='visitor_type',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_type',
        ),
    ]
